services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.ci
    image: jenkins-ci:latest
    ports:
      - "8000:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./casc:/var/jenkins_home/casc
      - ./az-creds.json:/var/jenkins_home/az-creds.json:ro
    restart: unless-stopped

volumes:
  jenkins_home:
