services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.ci
    image: jenkins-ci:latest
    ports:
      - "8000:8080"
      - "50000:50000"
    env_file:
      - .env
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      TENANT_ID: ${TENANT_ID}
      SUBSCRIPTION_ID: ${SUBSCRIPTION_ID}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./casc:/var/jenkins_home/casc
    restart: unless-stopped

volumes:
  jenkins_home:
